# -*- coding: utf-8 -*-
"""Rating.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XEWtOWKLEg3wkLPq5r1Yzj0owOGaWUcY
"""

from mrjob.job import MRJob
from mrjob.step import MRStep

class RatingsBreakdown(MRJob):
    def steps(self):
        return [
            MRStep(mapper=self.mapper_get_user,
                   reducer=self.reducer_count_user)
          ]

    def mapper_get_user(self, _, line):
        (userID, movieID, rating, timestamp) = line.split('\t')
        yield rating, 1

    def reducer_count_user(self, key, values):
        yield key, sum(values)

if __name__ == '__main__':
    RatingsBreakdown.run()

