# -*- coding: utf-8 -*-
"""Rating.avg.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XEWtOWKLEg3wkLPq5r1Yzj0owOGaWUcY
"""

from mrjob.job import MRJob
from mrjob.step import MRStep

class AverageRating(MRJob):

    def steps(self):
        return [
            MRStep(
                mapper=self.mapper_get_ratings,
                reducer=self.reducer_calculate_average
            )
        ]

    def mapper_get_ratings(self, _, line):

        try:
            userID, movieID, rating, timestamp = line.split('\t')


            rating = float(rating)


            yield movieID, rating

        except ValueError:
            pass

    def reducer_calculate_average(self, movieID, ratings):
        total = 0
        count = 0

        for rating in ratings:
            total += rating
            count += 1

        average = total / count

        yield movieID, round(average, 2)

if __name__ == '__main__':
    AverageRating.run()